-- Create the crm_calls table
CREATE TABLE IF NOT EXISTS public.crm_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT REFERENCES public.crm_leads(id) ON DELETE CASCADE,
    ts BIGINT NOT NULL,
    status TEXT DEFAULT 'answered',
    type TEXT DEFAULT 'call',
    by_user_id TEXT,
    by_user_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_crm_calls_lead_id ON public.crm_calls(lead_id);
CREATE INDEX IF NOT EXISTS idx_crm_calls_ts ON public.crm_calls(ts);

-- Data migration (Backfill from crm_leads)
DO $$
DECLARE
    lead_row RECORD;
    history_item JSONB;
BEGIN
    FOR lead_row IN SELECT id, call_history FROM public.crm_leads WHERE call_history IS NOT NULL AND jsonb_typeof(call_history) = 'array' AND jsonb_array_length(call_history) > 0 LOOP
        FOR history_item IN SELECT * FROM jsonb_array_elements(lead_row.call_history) LOOP
            -- Check if it's an old legacy number or a new JSON object
            IF jsonb_typeof(history_item) = 'number' THEN
                -- Check if it already exists to be idempotent
                IF NOT EXISTS (SELECT 1 FROM public.crm_calls WHERE lead_id = lead_row.id AND ts = (history_item#>>'{}')::BIGINT) THEN
                    INSERT INTO public.crm_calls (lead_id, ts, status, type)
                    VALUES (lead_row.id, (history_item#>>'{}')::BIGINT, 'answered', 'call');
                END IF;
            ELSE
                IF NOT EXISTS (SELECT 1 FROM public.crm_calls WHERE lead_id = lead_row.id AND ts = (history_item->>'ts')::BIGINT) THEN
                    INSERT INTO public.crm_calls (lead_id, ts, status, type, by_user_id, by_user_name)
                    VALUES (
                        lead_row.id,
                        (history_item->>'ts')::BIGINT,
                        COALESCE(history_item->>'status', 'answered'),
                        COALESCE(history_item->>'type', 'call'),
                        history_item->>'by_user_id',
                        history_item->>'by_user_name'
                    );
                END IF;
            END IF;
        END LOOP;
    END LOOP;
END $$;
